<<<<<<< HEAD
package bitcamp.bootapp;

// import org.junit.Test;
// import static org.junit.Assert.*;

public class AppTest {
    // @Test public void appHasAGreeting() {
    //     App classUnderTest = new App();
    //     assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    // }
=======
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.bootapp;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    //@Test public void appHasAGreeting() {
    //    App classUnderTest = new App();
    //    assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    //}
>>>>>>> fe168bb4781b87d021b44abf4c31866959ff6805
}
